# Generated by Django 3.1.5 on 2021-04-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texteditor', '0002_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
    ]
